language: node_js

node_js:
  - '10'

services:
  - docker

before_install:
  - docker run -d --name mongodb -e MONGO_INITDB_ROOT_USERNAME=uniboard -e MONGO_INITDB_ROOT_PASSWORD=draobiun mongo:4

before_script:
  - yarn install

script:
  - yarn build

after_script:
  - docker stop mongodb
  - docker rm mongodb

deploy:
  provider: heroku
  api_key:
    secure: "EtmgIA2Gy638yWQiQFyvTlNEje5SrBXPXK8nJhh/9p3reZ1EkEQfO5XUg9JHGSQfCcy8luoWMiOxlny+CozrrAXb40m8jixgODzMzQouVcIWsJ8PySE78kD2JmyH3+8IRH15KebXr/wQpdCwnXmqTN0KiMG371t3ZPcr9T28hHxp11LCziLKNAvnrqr+AgOVUtZ9mLUDZAjBFB7kL2NKIVlrFTm5bLvMdGlch9TBVEn62JyxdbOSvmcfB32zswzYsV94iC+ObwuOdWCwhgcNTcpO6IDL5gSZ4diBEh4SfKNLt1mMbP+6gjawLb72bbI3SWVKxDIZXzBWzDuCqTNxWMPIOsU7GExT8VBifs24dVaNu642bdB/rNgCNi1JOeDz2STSwsAPLYFv6QU0Hxtj3XxRTVdNTE2A2mcPOYafHweW4PlCJOX+LtqyVTmVKQK7Fd5b3Z8On7fuQpBbYBuY4JMRn+vg++pJoxh+vbyLCyu6o8Nw+TN9COHkercnCg+TYao7GhSuDnmN/TMIprCa0ZMjXQCVVSoUX2Dn64m3C98YvKzLDb9uA5PyZ9TvEnNhMZjGsGf3pe1CYnSFJ9KZsr1Sgva3qdZleSHHMdn+/UvpJMbi0RJ1hR3aF22lH1cywdmQBeyqu/qP9C+jZlGvqSHd5Ekmbp0WPWdOagsN21c="
  app: uniboard-dev
  on:
    branch: develop
  skip_cleanup: true
