language: node_js
node_js:
  - "10"

services:
  - docker

before_install: >
  - docker run -d --name mongodb
    -e MONGO_INITDB_ROOT_USERNAME=uniboard
    -e MONGO_INITDB_ROOT_PASSWORD=draobiun
    mongo:4

before_script:
  - yarn install

script:
  - yarn build

after_script:
  - docker stop mongodb
  - docker rm mongodb
