language: node_js

node_js:
  - '10'

services:
  - docker

before_install:
  - docker run -d --name mongodb -e MONGO_INITDB_ROOT_USERNAME=uniboard -e MONGO_INITDB_ROOT_PASSWORD=draobiun mongo:4

before_script:
  - yarn install

script:
  - yarn build

after_script:
  - docker stop mongodb
  - docker rm mongodb

deploy:
  provider: heroku
  api_key:
    secure: "PVrIwH+5549nzB/PGjRkEmp2LUBg1WtNbD7os0dQNwRAkBLsR/XMDPEtjx9cfTY8M7kerof8ULXOfIv4n4aINOo7nwS6gSyj6SRGHjGnbpk7tdo34KM6r7LfLkVWcA5kGiw373u8FctUrjvWi3LhWoMd6RSodxyoVISiMmkH89bFDhpiLNhZgMBAZkicrN5PegTRagMNfljd7VWO/x4kfaRVVO77KAZ6PYeplm0h2E+PeNyR+ONB1mJ3i+9VGfMtMkM6u2ne5J9KkFJlldFWs9gVMPLeBLFVxMolU0tx6rrXPu6+DJCulCRkCl9NTeXBxnBmrbq4yd5ciwF4OR9lcwMsSQBN23OYMuhIOBwxp7G4cwujpELOyy0kpj5N8LGmAGErU52stccHbwijhsFU4Iy/aYVexMpG3r/cmOq9+/wTtH895cdMUjFWwYoIIcPaXSpkixGSIWu/+ufIcnDod0ejnZXu3ahFJTrJipLiViK4vo7od8DLdKAkJ7JhTje8KfoibxLHfoSPN5pl0QPRaxPBWerF4+VFnjW0IJyjvivRt5wQ0UXnVK6NV3EkPvtxNcYF1ew3+2f4sD3NFxWuQlzBmd4En4MGfnWCmJKsQlJbD46IEcWK4fZy+3rND6TOtl4uW8urJYnJQsuAUrcgFWHAtgGLNBTDhEAI7+sDvHo="
  app: uniboard-dev
  on:
    branch: develop
  skip_cleanup: true
