language: node_js

node_js:
  - '10'

services:
  - docker

before_install:
  - docker run -d --name mongodb -e MONGO_INITDB_ROOT_USERNAME=uniboard -e MONGO_INITDB_ROOT_PASSWORD=draobiun mongo:4

before_script:
  - yarn install

script:
  - yarn build

after_script:
  - docker stop mongodb
  - docker rm mongodb

deploy:
  provider: heroku
  api_key:
    secure: okFtey6Dhl+o1utDo55SpypYyF08QXnYwcNZreFJMaff11mLW8CdgJHbaeOqzi0SnI2YAhqYgA50WsIxwPnsrHlauunAbmOwBPTLKZ4VunBDjZpswvyHdwkBjF/A8oeC3zbV58CSns9fUq0DaPj6HfkPrG+tS6+GEk6/PTCuJ57nXkjqWKgWg++DjBefispiStVGIIHCo87rncWFZstHjWXX4yPHznzzlVGbN3P997FAc/cwuP2adRle5PCyLBTinr1BhP+EniP4Sa0FmYK9pacNw01ZFs0uCxSAv7wrL3PlhR6olqMhfeUbr8qecZPsU1ZTSneoSaiZaFB0baWebL2ycCT2fBIoQ6542/py0G/sSddozu+QoXCdHiK+msp/6j0NjJIsa6Qgu/ea59d2vI7o/sERrKqJoGat9R7fsOO9baIBF18KPPgXvxP0ot9aTSo3cKv4n5XLuIWmkQiuGTks+GpzXusTq3g9NLLMDugRiecEyaCEmRuFvtLlUX3rPOqJxx4PzLaEoy0MUVo4Wh59h5n/Azsbafyug/2Odab55o+53sDfumluJ+UOXN//I2PhX79cYipw1dNlb4wdskBRUCAdGuOIgQX9Z801zt8mbF8AkhQCEQxjl9txbjGu0UxMB6lB9etDNKnuli28DNRra8Y9M7QeSXcjfjrolhY=
  app: uniboard-dev
  on:
    branch: develop
  skip_cleanup: true
