version: "3.2"
services:

  mongo:
    image: mongo:4
    networks:
      - internal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: uniboard
      MONGO_INITDB_ROOT_PASSWORD: braobiun

  uniboard:
    build: .
    image: uniboard:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - internal
    command: "npx npm-run-all --serial migrate test"

networks:
  internal:
