version: "3.2"
services:

  mongo:
    image: mongo:4
    networks:
      - internal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: uniboardDB
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  uniboard:
    build: .
    image: uniboard:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - internal
    command: "npx npm-run-all --serial migrate start"
    environment:
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      MONGODB_USERNAME: uniboard
      MONGODB_PASSWORD: uniboard
      MONGODB_DATABASE: uniboardDB

networks:
  internal:
