version: "3.2"
services:

  mongo:
    image: mongo:4
    networks:
      - internal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: uniboard
      MONGO_INITDB_ROOT_PASSWORD: braobiun
      MONGO_INITDB_DATABASE: uniboard
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  uniboard:
    image: node:10
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: "npx npm-run-all --serial migrate dev"
    depends_on:
      - mongo
    networks:
      - internal
    environment:
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      MONGODB_USERNAME: uniboard
      MONGODB_PASSWORD: braobiun
      MONGODB_DATABASE: uniboard

networks:
  internal:
